import importlib.util
import io
import json
import os
import plistlib
from pathlib import Path
import subprocess
import struct
import sys
import tarfile
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zlib
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import snapshot

spec = importlib.util.spec_from_file_location("publish_release", ROOT / "scripts/publish-release.py")
publish = importlib.util.module_from_spec(spec)
spec.loader.exec_module(publish)

spec = importlib.util.spec_from_file_location("verify_artifacts", ROOT / "scripts/verify-artifacts.py")
artifacts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(artifacts)


class Inputs(unittest.TestCase):
    def test_valid_refs(self):
        for ref in ("main", "a" * 40, "A" * 40):
            snapshot.validate_inputs(ref, "1")

    def test_reject_ref_injection_and_other_refs(self):
        for ref in ("HEAD", "refs/heads/main", "v1.0", "a" * 39, "a" * 41, "main\n", "$(id)", "--help"):
            with self.subTest(ref=ref), self.assertRaises(ValueError):
                snapshot.validate_inputs(ref, "1")

    def test_bad_revisions(self):
        for value in ("0", "01", "-1", "1.0", "10000", "2\n", "$(id)", ""):
            with self.subTest(value=value), self.assertRaises(ValueError):
                snapshot.validate_inputs("main", value)

    def test_review_and_repository_gates(self):
        with self.assertRaises(ValueError):
            snapshot.validate_inputs("main", "1", True, False)
        with patch.dict(os.environ, {"GITHUB_REPOSITORY": snapshot.REPOSITORY, "GITHUB_REF": "refs/heads/main"}):
            snapshot.validate_inputs("main", "1", True, True)
        with patch.dict(os.environ, {"GITHUB_REPOSITORY": "other/repo", "GITHUB_REF": "refs/heads/main"}):
            with self.assertRaises(ValueError):
                snapshot.validate_inputs("main", "1", True, True)

    def test_revision_identity(self):
        sha = "a" * 40
        self.assertEqual(snapshot.identity(sha, "1", "1.13.2")["version"], "1.13.2-snapshot")
        self.assertEqual(snapshot.identity(sha, "9999", "1.13.2")["bundle_version"], "1.99.99")
        self.assertEqual(snapshot.identity(sha, "2", "1.13.2")["tag"], f"snapshot-{sha}-r2")

    def test_cask(self):
        data = snapshot.identity("a" * 40, "2", "1.13.2") | {"minimum_macos": "10.13"}
        cask = snapshot.cask(data, "b" * 64)
        self.assertIn('version "1.13.2-snapshot,' + "a" * 40 + '-r2"', cask)
        self.assertIn('depends_on macos: ">= 11"', cask)
        self.assertIn('conflicts_with cask: "gureumkim"', cask)
        self.assertIn('input_method "Gureum.app"', cask)
        self.assertNotIn("--no-quarantine", cask)

    def test_versions_are_separate_and_safe(self):
        data = snapshot.identity("a" * 40, "1", "1.13.2")
        self.assertEqual(data["short_version"], "1.13.2")
        self.assertEqual(data["bundle_version"], "1.0.1")
        self.assertEqual(data["pkg_version"], "1.0.1")
        self.assertIn("1.13.2-snapshot-" + "a" * 40, data["stem"])
        for version in ("1.13.3-snapshot", "1.13", "01.13.2", "1.13.2\n", '1.13.2"', "$(id)"):
            with self.subTest(version=version), self.assertRaises(ValueError):
                snapshot.identity("a" * 40, "1", version)

    def test_source_version_uses_explicit_version_or_nearest_tag_without_bumping(self):
        with tempfile.TemporaryDirectory() as temporary:
            repo = Path(temporary)
            (repo / "OSX").mkdir()
            config = repo / "OSX/Version.xcconfig"
            config.write_text("// Do not commit this file\n")
            with patch.object(snapshot, "run", side_effect=["1.13.2-27-g46c62e5", "1.13.2"]):
                version, evidence = snapshot.source_version(repo)
            self.assertEqual(version, "1.13.2")
            self.assertEqual(evidence["commits_since_tag"], 27)
            config.write_text("VERSION = 1.14.0\n")
            with patch.object(snapshot, "run") as git:
                self.assertEqual(snapshot.source_version(repo)[0], "1.14.0")
                git.assert_not_called()
            config.write_text("VERSION = 1.14.0-snapshot\n")
            with self.assertRaises(ValueError):
                snapshot.source_version(repo)
            config.write_text("// generated by upstream\n")
            with patch.object(snapshot, "run", return_value="unknown-27-g46c62e5"), self.assertRaises(ValueError):
                snapshot.source_version(repo)
            with patch.object(snapshot, "run", side_effect=["GureumKIM-1.11.1-rc1-2-gabc1234", "GureumKIM-1.11.1-rc1"]):
                self.assertEqual(snapshot.source_version(repo)[0], "1.11.1")

    def test_about_overlay_preserves_update_code_and_fails_on_upstream_changes(self):
        with tempfile.TemporaryDirectory() as temporary:
            repo = Path(temporary)
            (repo / "OSX").mkdir()
            menu = repo / "OSX/GureumMenu.swift"
            menu.write_text('    NSApp.orderFrontStandardAboutPanel(sender)\n    if info.update.version == info.current {}\n')
            updater = repo / "OSX/UpdateManager.swift"
            updater.write_text('guard info.update.version != info.current else { return }\n')
            original = updater.read_bytes()
            with patch.object(snapshot, "SOURCE", repo):
                snapshot.prepare_source()
                self.assertIn('"PersonalSnapshotVersion"', menu.read_text())
                self.assertIn('if info.update.version == info.current', menu.read_text())
                self.assertEqual(updater.read_bytes(), original)
                with self.assertRaises(RuntimeError):
                    snapshot.prepare_source()


class Packaging(unittest.TestCase):
    @staticmethod
    def write_pkg(path, data):
        package = (f'<pkg-info version="{data["pkg_version"]}"><bundle '
                   f'id="org.youknowone.inputmethod.Gureum" CFBundleVersion="{data["bundle_version"]}" '
                   f'CFBundleShortVersionString="{data["short_version"]}"/></pkg-info>').encode()
        distribution = (f'<installer-gui-script><product version="{data["pkg_version"]}"/>'
                        f'<pkg-ref version="{data["pkg_version"]}"/></installer-gui-script>').encode()
        toc = '<xar><toc>'
        offset = 0
        for name, content in (("PackageInfo", package), ("Distribution", distribution)):
            toc += (f'<file><name>{name}</name><data><offset>{offset}</offset><length>{len(content)}</length>'
                    '<encoding style="application/octet-stream"/></data></file>')
            offset += len(content)
        toc += '</toc></xar>'
        raw = toc.encode()
        compressed = zlib.compress(raw)
        path.write_bytes(struct.pack('>4sHHQQI', b'xar!', 28, 1, len(compressed), len(raw), 0)
                         + compressed + package + distribution)

    def test_installer_versions_reject_suffixes_and_mismatches(self):
        data = snapshot.identity("a" * 40, "1", "1.13.2")
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "fixture.pkg"
            self.write_pkg(path, data)
            snapshot.verify_flat_pkg(path, data)
            for key in ("pkg_version", "bundle_version", "short_version"):
                self.write_pkg(path, data | {key: data[key] + "-snapshot"})
                with self.subTest(key=key), self.assertRaises(RuntimeError):
                    snapshot.verify_flat_pkg(path, data)
            self.write_pkg(path, data)
            with self.assertRaisesRegex(RuntimeError, "no PackageInfo"):
                snapshot.verify_pkg_xml([], ET.fromstring('<installer-gui-script/>'), data)

    def test_macos_minimum_excludes_catalyst_and_ios(self):
        load_commands = '''Load command 0
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 13.0
Load command 1
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 6
    minos 14.0
      sdk 16.0
Load command 2
      cmd LC_BUILD_VERSION
 platform IOS
    minos 17.0
'''
        self.assertEqual(snapshot.macos_minimums(load_commands), ["11.0"])

    def test_legacy_and_symbolic_macos_minimum(self):
        self.assertEqual(snapshot.macos_minimums('''Load command 0
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 11.0
Load command 1
      cmd LC_BUILD_VERSION
 platform MACOS
    minos 12.0
'''), ["10.13", "12.0"])
        with self.assertRaisesRegex(RuntimeError, "no minimum"):
            snapshot.macos_minimums("Load command 0\n cmd LC_BUILD_VERSION\n platform 1\n")

    def test_packaged_metadata_must_match_even_with_valid_checksums(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            data = snapshot.identity("a" * 40, "1", "1.13.2") | {
                "builder_repository": snapshot.REPOSITORY, "builder_sha": "b" * 40,
                "run_url": "https://github.com/test/run", "run_attempt": "1", "minimum_macos": "11",
                "version_evidence": {"kind": "nearest-tag", "tag": "1.13.2"}}
            (directory / "metadata.json").write_text(json.dumps(data))
            (directory / "Package.resolved").write_bytes(b"lockfile fixture")
            (directory / "DISTRIBUTION.md").write_text("fixture")
            self.write_pkg(directory / f'{data["stem"]}.unsigned.pkg', data)

            def write_archive(name, members):
                with tarfile.open(directory / name, "w:gz") as archive:
                    for path, contents in members.items():
                        member = tarfile.TarInfo(path)
                        member.size = len(contents)
                        archive.addfile(member, io.BytesIO(contents))

            info = {"CFBundleVersion": data["bundle_version"],
                    "CFBundleShortVersionString": data["short_version"],
                    "PersonalSnapshotVersion": data["version"],
                    "PersonalSnapshotUpstreamSHA": data["upstream_sha"],
                    "LSMinimumSystemVersion": data["minimum_macos"]}
            resources = "Gureum.app/Contents/Resources/PersonalSnapshot"
            app_members = {"Gureum.app/Contents/Info.plist": plistlib.dumps(info),
                           "Gureum.app/Contents/Resources/Preferences.prefPane/Contents/Info.plist": plistlib.dumps(info),
                           f"{resources}/metadata.json": json.dumps(data).encode(),
                           f"{resources}/Package.resolved": b"lockfile fixture"}
            write_archive(f'{data["stem"]}.app.tar.gz', app_members)
            write_archive(f'{data["stem"]}.source.tar.gz', {
                "build-info/metadata.json": json.dumps(data).encode(),
                "build-info/Package.resolved": b"lockfile fixture",
                "build-info/upstream-build-changes.diff": b"",
                "gureum/COPYING": b"notice fixture"})
            write_archive("licenses.tar.gz", {"licenses/gureum/COPYING": b"notice fixture"})
            with patch.object(snapshot, "DIST", directory):
                snapshot.finalize()
            self.assertEqual(artifacts.verify(directory, "b" * 40)["checksums_verified"], 9)
            # A freshly recalculated checksum must not mask conflicting embedded SHA.
            for key, value in (("PersonalSnapshotUpstreamSHA", "c" * 40),
                               ("LSMinimumSystemVersion", "10.13"),
                               ("PersonalSnapshotVersion", "1.13.3-snapshot"),
                               ("CFBundleShortVersionString", "1.13.2-snapshot"),
                               ("CFBundleVersion", "1.0.1-snapshot")):
                app_members["Gureum.app/Contents/Info.plist"] = plistlib.dumps(info | {key: value})
                write_archive(f'{data["stem"]}.app.tar.gz', app_members)
                with patch.object(snapshot, "DIST", directory):
                    snapshot.finalize()
                with self.subTest(key=key), self.assertRaisesRegex(ValueError, "provenance mismatch"):
                    artifacts.verify(directory, "b" * 40)

    def test_tracked_archive_excludes_git_and_untracked_files(self):
        with tempfile.TemporaryDirectory() as temporary:
            repo = Path(temporary) / "repo"
            repo.mkdir()
            subprocess.run(["git", "init", "-q", str(repo)], check=True)
            (repo / "COPYING").write_text("test notice")
            subprocess.run(["git", "add", "COPYING"], cwd=repo, check=True)
            subprocess.run(["git", "-c", "user.name=Test", "-c", "user.email=test@example.invalid",
                            "commit", "-qm", "fixture"], cwd=repo, check=True)
            (repo / "not-source.secret").write_text("excluded")
            output = Path(temporary) / "source.tar.gz"
            with tarfile.open(output, "w:gz") as archive:
                snapshot.add_git_archive(archive, repo, "gureum")
            with tarfile.open(output) as archive:
                self.assertEqual(archive.getnames(), ["gureum/COPYING"])
                self.assertEqual(archive.extractfile("gureum/COPYING").read(), b"test notice")

    def test_payload_and_checksum_verification(self):
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            data = snapshot.identity("a" * 40, "1", "1.13.2") | {
                "builder_repository": snapshot.REPOSITORY, "builder_sha": "b" * 40,
                "run_url": "https://github.com/test/run", "run_attempt": "1", "minimum_macos": "11",
                "version_evidence": {"kind": "nearest-tag", "tag": "1.13.2"}}
            (directory / "metadata.json").write_text(json.dumps(data))
            for suffix in ("app.tar.gz", "unsigned.pkg", "source.tar.gz"):
                (directory / f'{data["stem"]}.{suffix}').write_bytes(b"test fixture, not a real app")
            for name in ("Package.resolved", "licenses.tar.gz", "DISTRIBUTION.md"):
                (directory / name).write_text("fixture")
            with patch.object(snapshot, "DIST", directory):
                snapshot.finalize()
            verified, files = publish.verify_payload(directory, "b" * 40)
            self.assertEqual(verified["tag"], data["tag"])
            self.assertEqual(len(files), 10)
            (directory / "DISTRIBUTION.md").write_text("tampered")
            with self.assertRaises(ValueError):
                publish.verify_payload(directory, "b" * 40)

    def test_api_errors_fail_closed(self):
        failure = subprocess.CompletedProcess([], 1, stdout="", stderr="gh: Forbidden (HTTP 403)")
        with patch.object(subprocess, "run", return_value=failure), self.assertRaises(RuntimeError):
            publish.api_get("test")
        missing = subprocess.CompletedProcess([], 1, stdout="", stderr="gh: Not Found (HTTP 404)")
        with patch.object(subprocess, "run", return_value=missing):
            self.assertIsNone(publish.api_get("test"))


if __name__ == "__main__":
    unittest.main()
